## Importación de librerias

In [65]:
# importamos las librerias necesarias
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Carga del archivo CSV

In [68]:
# cargar el documento csv con pd.read_csv, creando el dataframe
df = pd.read_csv('/Users/stam/Documents/Documents_MacBook_Eduardo/GitHub/jumping_spider_salticidae/datasets/salticidae_mexico_conabio.csv')

## Limpiesa de datos

In [73]:
# se verifica la completitud de las variables (valores nulos existentes)
# se utiliza la función .sum() para sumar los elementos que están vacíos (.isnull())
nulos = df.isnull().sum()

# calculo del porcentaje de completitud
completitud = pd.DataFrame(100 - (nulos / len(df) * 100))

# reset_index se utiliza para resetear los índices
# inplace = True sirve para evitar la repetición
completitud.reset_index(inplace = True)
# se coloan encebezados
completitud = completitud.rename(columns = {"index":"variable",0:"completitud"})

# ordenamos las columnas con mayot completitud en adelante
completitud.sort_values(by='completitud', ascending=True).head(10)

                        variable  completitud
48  categoriainfraespecie2valida          0.0
91        vegetacionserenanalcms          0.0
53       categoriaresidenciaaves          0.0
66                     endemismo          0.0
54            formadecrecimiento          0.0
64                nivelprioridad          0.0
63                   prioritaria          0.0
62                        nom059          0.0
61                          iucn          0.0
60                         cites          0.0

In [75]:
# filtrar  arañas encontradas en México
df = df[df['paisoriginal'].str.contains('Mexico', na=False, case=False)]

In [77]:
# eliminacion de los datos duplicados
df.drop_duplicates(inplace=True)

# eliminacion de los datos faltantes
df = df.dropna(subset=[ 'paiscoleccion','familiavalida','generovalido','estadooriginal'])

# .fillna reemplazará todos los valores NaN (vacíos) en la columna "especievalida" con "sp."
# .replace reemplazará las celdas vacías ("") con ".sp" en la columna "especievalida"
df['especievalida'] = df['especievalida'].fillna('sp.').replace('', 'sp.')

In [79]:
# las columnas con menos del 80% de completitud son eliminadas
# define una serie de pandas  con el nombre de las columnas
cols_incompletas = completitud['variable'][completitud['completitud']<80]
# se eliminan esas columnas
df = df.drop(cols_incompletas, axis=1) # 1 columnas 0 filas
df.head(2)

,idejemplar,coleccion,institucion,paiscoleccion,fechacolecta,diacolecta,mescolecta,aniocolecta,fechadeterminacion,diadeterminacion,...,altitudmapa,geovalidacion,validacionambiente,usvserieI,usvserieII,usvserieIII,usvserieIV,usvserieV,usvserieVI,geoportal
0,11f9827c7db57a6ad07e10ff827ab5c3,MACN-Ar Colección Nacional de Aracnología,MACN Museo Argentino de Ciencias Naturales Ber...,ARGENTINA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sin coordenadas,No procesado,NaN,NaN,NaN,NaN,NaN,NaN,0
1,82a23e1556b9ca2a7610a8b955ecf4c1,MACN-Ar Colección Nacional de Aracnología,MACN Museo Argentino de Ciencias Naturales Ber...,ARGENTINA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sin coordenadas,No procesado,NaN,NaN,NaN,NaN,NaN,NaN,0

In [83]:
# se verifica la completitud de las variables (valores nulos existentes)
# se utiliza la función .sum() para sumar los elementos que están vacíos (.isnull())
nulos = df.isnull().sum()

# calculo del porcentaje de completitud
completitud = pd.DataFrame(100 - (nulos / len(df) * 100))

# reset_index se utiliza para resetear los índices
# inplace = True sirve para evitar la repetición
completitud.reset_index(inplace = True)
# se coloan encebezados
completitud = completitud.rename(columns = {"index":"variable",0:"completitud"})

In [57]:
completitud.sort_values(by='completitud', ascending=True).head(60)

                    variable  completitud
28                     autor    85.649394
24                   especie    85.649394
25                estatustax    85.649394
9           diadeterminacion    86.313930
8         fechadeterminacion    86.313930
10          mesdeterminacion    86.902759
11         aniodeterminacion    87.600942
15                 urlorigen    88.307537
59                 usvserieI    91.470390
62                usvserieIV    91.773217
60                usvserieII    91.773217
61               usvserieIII    91.781629
64                usvserieVI    91.781629
56               altitudmapa    92.000336
50        clavemunicipiomapa    92.168573
49                estadomapa    92.168573
52             municipiomapa    92.168573
47           claveestadomapa    92.168573
63                 usvserieV    92.513459
55                     datum    92.530283
44                   latitud    92.530283
43                  longitud    92.530283
46                  paismapa    92.530283
51         municipiooriginal    93.733176
39                  ambiente    94.313594
5                 diacolecta    99.125168
4               fechacolecta    99.125168
53                 localidad    99.444818
16  ultimafechaactualizacion    99.486878
6                 mescolecta    99.503701
7                aniocolecta    99.528937
38               autorvalido    99.671938
54                    region   100.000000
57             geovalidacion   100.000000
48            estadooriginal   100.000000
58        validacionambiente   100.000000
45              paisoriginal   100.000000
42             taxonvalidado   100.000000
41               subgrupobio   100.000000
0                 idejemplar   100.000000
32               ordenvalido   100.000000
37              reftaxvalido   100.000000
1                  coleccion   100.000000
2                institucion   100.000000
3              paiscoleccion   100.000000
12       procedenciaejemplar   100.000000
13              formadecitar   100.000000
14                  proyecto   100.000000
17                   version   100.000000
18                     reino   100.000000
19            phylumdivision   100.000000
20                     clase   100.000000
40                  grupobio   100.000000
21                     orden   100.000000
23                    genero   100.000000
26               idnombrecat   100.000000
27                    reftax   100.000000
29               reinovalido   100.000000
30      phylumdivisionvalido   100.000000
31               clasevalida   100.000000

In [85]:
# dimensión del dataframe con eliminacion de datos duplicados
print(f"Número de filas: {df.shape[0]}")
print(f"Número de columnas: {df.shape[1]}")

Número de filas: 11888
Número de columnas: 66

### Guardar dataframes en archivos CSV

In [39]:
# Guardar el dataframe en un archivo CSV
df.to_csv('salticidae_mexico_conabio.csv', index=False)

print("DataFrame guardado en salticidae_mexico_conabio.csv")

DataFrame guardado en salticidae_mexico_conabio.csv